HW13 is completed
maraero/otus-go pull request #14
Opened 2022-12-28 15:10 UTC by maraero

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-28 15:13 UTC, maraero commented
Нужна помощь с процессом остановки работы приложения
Сейчас, если выключаю приложение, запущенное через `make run`, получаю панику примерно такого содержания:
```
^C{"level":"INFO","time":"2022-12-28T18:13:00.250+0300","message":"[calendar is turning off...]"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x14143a5]

goroutine 21 [running]:
google.golang.org/grpc.(*Server).GracefulStop(0x0)
        /Users/evgeniy.kudriavtsev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1841 +0x45
github.com/maraero/otus-go/hw12_13_14_15_calendar/internal/servers/grpc.(*Server).Stop(...)
        /Users/evgeniy.kudriavtsev/Documents/Study/otus-go/hw12_13_14_15_calendar/internal/servers/grpc/server.go:33
main.shutDown.func3()
        /Users/evgeniy.kudriavtsev/Documents/Study/otus-go/hw12_13_14_15_calendar/cmd/calendar/main.go:109 +0x5d
created by main.shutDown
        /Users/evgeniy.kudriavtsev/Documents/Study/otus-go/hw12_13_14_15_calendar/cmd/calendar/main.go:107 +0x218
make: *** [run] Error 2
```

Никак не могу разобраться, в чём дело :(

2022-12-28 16:25 UTC, dshemin requested changes

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/api/event_service/event_service.proto
> +    rpc UpdateEvent(UpdateEventRequest) returns (UpdateEventResposnse) {}
Совет:

`UpdateEventResponse` а не `UpdateEventResposnse`

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/internal/event-service/storage-sql/storage.go
> +func (s *Storage) GetEventByID(ctx context.Context, id int64) (evt.Event, error) {
Критично:

Проверьте правильность работы данной функции.

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/internal/servers/grpc/interface.go
> +package servergrpc
Важно:

Неудачное название файла. Когда видишь файл с названием `interface.go` ожидаешь увидеть там интерфейсы, а не структуру сервера.

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/internal/servers/grpc/server_test.go
> +	config, err := config.New("../../../configs/config_test.json")
Совет:

Мы пишем юнит-тесты для GRPC. В юнит-тестах мы проверяем код тестируемого функционала и мокаем всё остальное. Поэтому, будет проще просто создать структуру конфига с необходимыми параметрами и всё.

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/internal/servers/grpc/server_test.go
> +	if err != nil {
Важно:

`github.com/stretchr/testify/require.NoError`. Советую ознакомится с документацией методов `github.com/stretchr/testify/require` и `github.com/stretchr/testify/assert`. Это позволит вам очень сильно уменьшить кода в тестах и сделает их более легко читаемыми.

2022-12-28 16:25 UTC, dshemin commented on hw12_13_14_15_calendar/internal/servers/grpc/server_test.go
> +	var dbConnection *sqlx.DB
Критично:

Что произойдёт если тестируемый нами код попробует обратится к БД? Используйте интерфейсы и моки.

2022-12-28 17:25 UTC, maraero commented on hw12_13_14_15_calendar/internal/event-service/storage-sql/storage.go
> +func (s *Storage) GetEventByID(ctx context.Context, id int64) (evt.Event, error) {
Дело же в том, что я использую `Get` вместо `Named...` метода?

2022-12-28 17:44 UTC, maraero commented on hw12_13_14_15_calendar/internal/servers/grpc/server_test.go
> +	var dbConnection *sqlx.DB
На самом деле ничего не произойдёт:
https://github.com/maraero/otus-go/blob/d6e03475dfe6c1baeeee4b014157fc88ec6ce3dc/hw12_13_14_15_calendar/internal/event-service/service/event_service.go#L13

Сервис увидит, что базы нет и начнёт использовать in-memory реализацию.

Как лучше поступать в таких случаях? Создать абстракцию для подключения к хранилищу?

Почему я сделал так?
Потому что хотел использовать одно и то же соединение и для возможных миграций, и для других будущих сервисов:
https://github.com/maraero/otus-go/blob/d6e03475dfe6c1baeeee4b014157fc88ec6ce3dc/hw12_13_14_15_calendar/cmd/calendar/main.go#L71
Могу исправить это в следующем задании?

2022-12-29 09:51 UTC, maraero commented on hw12_13_14_15_calendar/internal/servers/grpc/server_test.go
> +	var dbConnection *sqlx.DB
В итоге переделал - вынес абстракцию `Storage`, которая уже определяет, что за подключение используется. `EventService` уже зависит от `Storage` и дальше решает, какой репозиторий использовать для работы с данными (память или sql)

2022-12-31 18:40 UTC, dshemin approved these changes

2022-12-31 18:40 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/constants.go
> +const (
Совет:

Если создаёте перечисление, то принято сначала объявить тип и после него сразу объявлять значения этого перечисления, после пустой строки.

2023-01-01 15:59 UTC, merged